### ISSUE TITLE
PaperMC 1.16.3

### ISSUE THREAD

**Issue by xCraimax** [strumswell/ServerlistMOTD-X#17]
Hello, i installed ServerListMotd-X and configured it but every time when i refresh my server list a get a big error Message and the Plugin doesnt give me the correct MOTD.

The Error: 
[17:43:25 ERROR]: Could not pass event StandardPaperServerListPingEventImpl to ServerlistMOTD vX-2020-09-05
java.lang.NullPointerException: null
at cloud.bolte.serverlistmotd.variables.WeatherVariable.getWeather(WeatherVariable.java:27) ~[?:?]
at cloud.bolte.serverlistmotd.motd.ClassicMotd.formatMotd(ClassicMotd.java:41) ~[?:?]
at cloud.bolte.serverlistmotd.motd.ClassicMotd.setServerlistMotd(ClassicMotd.java:57) ~[?:?]
at cloud.bolte.serverlistmotd.events.Ping.onPing(Ping.java:28) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor644.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-198]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.3.jar:git-Paper-198]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-198]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-198]
at com.destroystokyo.paper.network.StandardPaperServerListPingEventImpl.processRequest(StandardPaperServerListPingEventImpl.java:80) ~[patched_1.16.3.jar:git-Paper-198]
at net.minecraft.server.v1_16_R2.PacketStatusListener.a(PacketStatusListener.java:136) ~[patched_1.16.3.jar:git-Paper-198]
at net.minecraft.server.v1_16_R2.PacketStatusInStart.a(SourceFile:22) ~[patched_1.16.3.jar:git-Paper-198]
at net.minecraft.server.v1_16_R2.PacketStatusInStart.a(SourceFile:8) ~[patched_1.16.3.jar:git-Paper-198]
at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:159) ~[patched_1.16.3.jar:git-Paper-198]
at net.minecraft.server.v1_16_R2.NetworkManager.channelRead0(NetworkManager.java:148) ~[patched_1.16.3.jar:git-Paper-198]
at net.minecraft.server.v1_16_R2.NetworkManager.channelRead0(NetworkManager.java:30) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-198]
at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:263) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:147) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[patched_1.16.3.jar:git-Paper-198]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.16.3.jar:git-Paper-198]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**Comment by xCraimax** [comment]
i dont know how but i fixed it... Sorry

**Comment by strumswell** [comment]
Just out of curiosity: What happened and what did you do/ happen that made it work again? Looks like something was not working with the weather variable.
