### ISSUE TITLE
vault integration bug

### ISSUE THREAD

**Issue by NoopyyGaming** [strumswell/ServerlistMOTD-X#2]
Hi !

i'm using your plugin on my localhost server, and when the server is fully loaded, the plugin shows me this error : 

`[11:50:06] [Server thread/ERROR]: Error occurred while enabling ServerlistMOTD vX-2018-10-20 (Is it up to date?)
java.lang.NullPointerException
	at cloud.bolte.serverlistmotd.util.VaultIntegration.setupChat(VaultIntegration.java:25) ~[?:?]
	at cloud.bolte.serverlistmotd.util.VaultIntegration.setupVault(VaultIntegration.java:60) ~[?:?]
	at cloud.bolte.serverlistmotd.Main.onEnable(Main.java:74) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`

**Comment by strumswell** [comment]
Hey! Can you give me the following information:

- Spigot Version
- ServerlistMOTD Version
- Vault Version
- Economy Plugin if you have it
- Full Serverlog

Happy to help :-)

**Comment by NoopyyGaming** [comment]
Hi !
Sure, there you go : 

● git-Spigot-21fe707 --> Spigot 1.8.8-R0.1-SNAPSHOT
● ServerlistMOTD Version X-2018-10-20
● Vault Version 1.7.2-b107
● Economy used from Essentials & Vault
● Server Logs : https://pastebin.com/YCw4n0Ek

Best Regards

**Comment by strumswell** [comment]
Thank. Gonna look into it tonight.

**Comment by NoopyyGaming** [comment]
> 
> 
> Thanks. Gonna look into it tonight.

Alright, no problem. And by the way, thanks =)

**Comment by strumswell** [comment]
Hey, quick update from my side. I was using multiple functions in my vault integration which were never used and caused some problems. Please try this build and report back. :)

[ServerlistMOTD.zip](https://github.com/strumswell/ServerlistMOTD-X/files/4271889/ServerlistMOTD.zip)

**Comment by NoopyyGaming** [comment]
> 
> 
> Hey, quick update from my side. I was using multiple functions in my vault integration which were never used and caused some problems. Please try this build and report back. :)
> 
> [ServerlistMOTD.zip](https://github.com/strumswell/ServerlistMOTD-X/files/4271889/ServerlistMOTD.zip)

Hello !

It works now. :)
just asking you, what's this with Vault : Using net.milkbowl.vault.economy.plugins.Economy_Essentials@318daf75 via Vault.

Is it normal or it's only a message to say something ?

**Comment by strumswell** [comment]
Great to hear. I’m going to wait a day or so before releasing the fix. So if anything doesn’t work correctly, please let me know right here. :-)

Regarding this message: I thought it would be a good idea to communicate the economy plugins ServerlistMOTD taps into. Makes it clear to the user that the integration works and might be helpful for debugging errors. 

Thanks for reporting the bug. 👍✅

**Comment by NoopyyGaming** [comment]
> 
> 
> Great to hear. I’m going to wait a day or so before releasing the fix. So if anything doesn’t work correctly, please let me know right here. :-)
> 
> Regarding this message: I thought it would be a good idea to communicate the economy plugins ServerlistMOTD taps into. Makes it clear to the user that the integration works and might be helpful for debugging errors.
> 
> Thanks for reporting the bug. 👍✅

Hi !

Sure i will, don't worry, if i got anything with the plugin, you'll know it ;-)
Nice work, keep it up dude 👍
