### ISSUE TITLE
Plugins dont work

### ISSUE THREAD

**Issue by NockyCZ** [strumswell/ServerlistMOTD-X#42]
Hey, please how i can fix this? 

Could not load 'plugins/ServerlistMOTD.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: cloud/bolte/serverlistmotd/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [minecraft_server.jar:git-Spigot-e4d4710-e1ebe52]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]

I have this java version: Java SE 8u311

**Comment by strumswell** [comment]
Hey, which Java version do you have? You seem to use an older one. Please consider updating Java. :)

Edit: oh, you have already shared your Java version. Please try updating it :)
